spring:
  application:
    name: nequi
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:franquicias}
    username: ${POSTGRES_USER:franquicias}
    password: ${POSTGRES_PASSWORD:franquicias}
  jpa:
    hibernate:
      ddl-auto: validate
